name: CI

on:
  push:
    branches: main
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  RUNNER : windows-latest
jobs:
  build:
    environment: Development
    runs-on: ${{secrets.RUNNER}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
